### ISSUE TITLE
More gas consumption while Running the loop

### ISSUE THREAD

**Issue by ompatil1357** [sarvesh371/calendar-smart-contract#1]
While you are running the loop in the function "Create loop". you can add alternative to reduce gas consumption.

![Screenshot (74)](https://github.com/user-attachments/assets/9ea4a0b0-53f3-436b-b643-ac9f6a80f9e0)

**Comment by sarvesh371** [comment]
@ompatil1357 Thanks for raising this issue. Would you like to raise a fix for this?
